=== adsabs/ingest_data_model/adsingestschema/Document.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Document",
  "description": "Data schema for importing metadata into ADS pipeline",
  "type": "object",
  "properties": {
    "recordData": {
      "$ref": "./RecordData.json"
    },
    "relatedTo": {
      "type": "array",
      "description": "Array of RelatedTo.json objects",
      "items": {
        "$ref": "./RelatedTo.json"
      }
    },
    "editorialHistory": {
      "$ref": "./EdHist.json"
    },
    "pubDate": {
      "$ref": "./PubDates.json"
    },
    "publication": {
      "$ref": "./Publication.json"
    },
    "persistentIDs": {
      "type": "array",
      "description": "Array of PersistentID.json objects",
      "items": {
        "$ref": "./PersistentID.json"
      }
    },
    "publisherIDs": {
      "type": "array",
      "description": "Array of PublisherID.json objects",
      "items": {
        "$ref": "./PublisherID.json"
      }
    },
    "pagination": {
      "$ref": "./Pagination.json"
    },
    "authors": {
      "type": "array",
      "description": "Array of Contrib objects",
      "items": {
        "$ref": "./Contrib.json"
      }
    },
    "otherContributor": {
      "type": "array",
      "description": "Array of Contrib/role pairs",
      "items": {
        "$ref": "./OtherContrib.json"
      }
    },
    "title": {
      "type": "object",
      "properties": {
        "textEnglish": {
          "type": "string"
        },
        "textNative": {
          "type": "string"
        },
        "langNative": {
          "type": "string"
        }
      }
    },
    "subtitle": {
      "type": "string"
    },
    "abstract": {
      "type": "object",
      "properties": {
        "textEnglish": {
          "type": "string"
        },
        "textNative": {
          "type": "string"
        },
        "langNative": {
          "type": "string"
        }
      }
    },
    "comments": {
      "type": "array",
      "description": "Comments from authors, etc.",
      "items": {
        "$ref": "./Comment.json"
      }
    },
    "fulltext": {
      "type": "object",
      "description": "Contains the body of the fulltext document, and its language",
      "$comment": "Body is free format and could (for example) contain the entire file",
      "properties": {
        "language": {
          "type": "string"
        },
        "body": {
          "type": "string"
        }
      }
    },
    "acknowledgements": {
      "type": "string",
      "description": "Acknowledgements, if fielded separately from body"
    },
    "references": {
      "type": "array",
      "description": "List of references in free text format",
      "items": {
        "type": "string"
      }
    },
    "backmatter": {
      "type": "array",
      "description": "Appendices, Supplementary material.",
      "items": {
        "type": "object",
        "properties": {
          "backType": {
            "type": "string"
          },
          "language": {
            "type": "string"
          },
          "body": {
            "type": "string"
          }
        }
      }
    },
    "astronomicalObjects": {
      "type": "array",
      "description": "List of astronomical objects in free text format",
      "items": {
        "type": "string"
      }
    },
    "esources": {
      "type": "array",
      "description": "Array of ESource.json objects",
      "items": {
        "$ref": "./ESource.json"
      }
    },
    "dataLinks": {
      "type": "array",
      "description": "Array of DataLink.json objects",
      "items": {
        "$ref": "./DataLink.json"
      }
    },
    "doctype": {
      "type": "string",
      "description": "This will only be required if we set doctype at parsing",
      "enum": [
        "article",
        "eprint",
        "phdthesis",
        "mastersthesis",
        "book",
        "inbook",
        "proceedings",
        "inproceedings",
        "software",
        "talk",
        "abstract",
        "proposal",
        "pressrelease",
        "circular",
        "newsletter",
        "catalog",
        "misc",
        "techreport",
        "nonarticle",
        "dataset"
      ]
    },
    "keywords": {
      "type": "array",
      "description": "Array of Keyword.json objects",
      "items": {
        "$ref": "./Keyword.json"
      }
    },
    "copyright": {
      "type": "object",
      "properties": {
        "status": {
          "type": "boolean"
        },
        "statement": {
          "type": "string"
        }
      }
    },
    "openAccess": {
      "$ref": "./OpenAccess.json"
    },
    "pubnote": {
      "type": "string"
    },
    "funding": {
      "type": "string"
    },
    "version": {
      "type": "string"
    }
  },
  "required": [
    "recordData",
    "title",
    "pubDate",
    "publication"
  ],
  "additionalProperties": false
}

=== adsabs/ingest_data_model/test_data/gcnc.json
{
  "recordData": {
    "createdTime": "2021-08-30Z12:00:00",
    "parsedTime": "2021-10-02Z18:50:00",
    "loadType": "fromFile",
    "loadFormat": "Text",
    "loadLocation": "./real_data/14500.gcn3",
    "recordOrigin": "Publisher"
  },
  "pubDate": {
    "electrDate": "2013-04-29"
  },
  "title": {
    "textEnglish": "GRB 100728A: GROND host detection and X-shooter redshift"
  },
  "authors": [
    {
      "name": {
        "surname": "Kruehler",
        "given-name": "T."
      },
      "affiliation": [
        {
          "affPubRaw": "DARK"
        }
      ]
    },
    {
      "name": {
        "surname": "Greiner",
        "given-name": "J."
      },
      "affiliation": [
        {
          "affPubRaw": "MPE"
        }
      ]
    },
    {
      "name": {
        "surname": "Kann",
        "given-name": "D.A."
      },
      "affiliation": [
        {
          "affPubRaw": "TLS"
        }
      ]
    }
  ],
  "publication": {
    "docType": "article",
    "pubName": "GCN Circular",
    "publisher": "NASA Goddard Space Flight Center",
    "volumeNum": "14500",
    "pubYear": "2013"
  },
  "pagination": {
    "firstPage": "1"
  },
  "abstract": {
    "textEnglish": "TITLE:   GCN CIRCULAR\nNUMBER:  14500\nSUBJECT: GRB 100728A: GROND host detection and X-shooter redshift\nDATE:    13/04/29 11:32:33 GMT\nFROM:    Thomas Kruehler at Dark Cosmology Center  <tom@dark-cosmology.dk>\n\nT. Kruehler (DARK), J. Greiner (MPE) and D. A. Kann (TLS) report:\n\nWe performed deep observations of the field of GRB 100728A\nsimultaneously in g'r'i'z'JHK with GROND (Greiner et al. 2008,\nPASP 120, 405). GRB 100728A triggered Swift (Cannizzo et al.,\nGCN 11004), GBM (von Kienlin, GCN 11006), Konus-Wind (Golenetskii\net al., GCN 11021) and Suzaku WAM (Tsai et al., GCN 11037).\n\nOur late observations were performed on 2010-11-10, 105 days\nafter the trigger, and consisted of dithered images with a total of\n4427 s exposure in g'r'i'z' and 3600 s in JHK under clear sky\nconditions and a seeing of 0.8\".\n\nInside the enhanced X-ray error-circle\n(http://www.swift.ac.uk/xrt_positions), we detect an extended\nobject with an r'-band AB magnitude of r' = 25.0 +/- 0.2.\n\nIts barycentric coordinates are:\n\nRA (J2000) = 05:55:01.98\nDec. (J2000) = -15:15:19.7\n\nwith uncertainties of 0.3\" in each coordinate.\nRegistering the early afterglow images (Olivares et al., GCN 11020)\nagainst the late host frame, we derive an offset between galaxy\ncenter and afterglow of approximately 0.4\".\n\nA spectrum of this galaxy was taken on 2012-11-15 with the ESO VLT\nUT2 equipped with the X-shooter spectrograph, covering the\nwavelength range 3000-25000 AA. The seeing was 1.2\" and the\ntotal exposure of our spectrum was 2400 s. In the VIS and NIR arm,\nwe detect emission lines, which we interpret as being due to\n[O II](3729) and Halpha at a common redshift of z = 1.567.\n\nThe bright X-ray emission (Evans et al., GCN 11014), coupled with the\nfaint and red optical/NIR afterglow (Olivares et al., GCN 11020) is\ncharacteristic of dust-extinguished events. Fitting the available\nafterglow data with synchrotron models, the visual extinction along\nthe GRB sightline is constrained to 1.5 mag < A_V < 3 mag at z = 1.567.\n\n"
  },
  "fulltext": {
    "language": "en",
    "body": "TITLE:   GCN CIRCULAR\nNUMBER:  14500\nSUBJECT: GRB 100728A: GROND host detection and X-shooter redshift\nDATE:    13/04/29 11:32:33 GMT\nFROM:    Thomas Kruehler at Dark Cosmology Center  <tom@dark-cosmology.dk>\n\nT. Kruehler (DARK), J. Greiner (MPE) and D. A. Kann (TLS) report:\n\nWe performed deep observations of the field of GRB 100728A\nsimultaneously in g'r'i'z'JHK with GROND (Greiner et al. 2008,\nPASP 120, 405). GRB 100728A triggered Swift (Cannizzo et al.,\nGCN 11004), GBM (von Kienlin, GCN 11006), Konus-Wind (Golenetskii\net al., GCN 11021) and Suzaku WAM (Tsai et al., GCN 11037).\n\nOur late observations were performed on 2010-11-10, 105 days\nafter the trigger, and consisted of dithered images with a total of\n4427 s exposure in g'r'i'z' and 3600 s in JHK under clear sky\nconditions and a seeing of 0.8\".\n\nInside the enhanced X-ray error-circle\n(http://www.swift.ac.uk/xrt_positions), we detect an extended\nobject with an r'-band AB magnitude of r' = 25.0 +/- 0.2.\n\nIts barycentric coordinates are:\n\nRA (J2000) = 05:55:01.98\nDec. (J2000) = -15:15:19.7\n\nwith uncertainties of 0.3\" in each coordinate.\nRegistering the early afterglow images (Olivares et al., GCN 11020)\nagainst the late host frame, we derive an offset between galaxy\ncenter and afterglow of approximately 0.4\".\n\nA spectrum of this galaxy was taken on 2012-11-15 with the ESO VLT\nUT2 equipped with the X-shooter spectrograph, covering the\nwavelength range 3000-25000 AA. The seeing was 1.2\" and the\ntotal exposure of our spectrum was 2400 s. In the VIS and NIR arm,\nwe detect emission lines, which we interpret as being due to\n[O II](3729) and Halpha at a common redshift of z = 1.567.\n\nThe bright X-ray emission (Evans et al., GCN 11014), coupled with the\nfaint and red optical/NIR afterglow (Olivares et al., GCN 11020) is\ncharacteristic of dust-extinguished events. Fitting the available\nafterglow data with synchrotron models, the visual extinction along\nthe GRB sightline is constrained to 1.5 mag < A_V < 3 mag at z = 1.567.\n\n"
  },
  "astronomicalObjects": [
    "GRB 100728A"
  ],
  "esources": [
    {
      "source": "pub_html",
      "location": "https://gcn.gsfc.nasa.gov/gcn/gcn3/14500.gcn3"
    }
  ]
}
