=== adsabs/ingest_data_model/json_schema/Document.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/adsabs/ingest_data_model/refs/tags/v1.1.0/json_schema/Document.json",
  "title": "Document",
  "description": "Data schema for importing metadata into ADS pipeline",
  "type": "object",
  "properties": {
    "recordData": {
      "$ref": "./RecordData.json"
    },
    "relatedTo": {
      "type": "array",
      "description": "Array of RelatedTo.json objects",
      "items": {
        "$ref": "./RelatedTo.json"
      }
    },
    "editorialHistory": {
      "$ref": "./EdHist.json"
    },
    "pubDate": {
      "$ref": "./PubDates.json"
    },
    "publication": {
      "$ref": "./Publication.json"
    },
    "persistentIDs": {
      "type": "array",
      "description": "Array of PersistentID.json objects",
      "items": {
        "$ref": "./PersistentID.json"
      }
    },
    "publisherIDs": {
      "type": "array",
      "description": "Array of PublisherID.json objects",
      "items": {
        "$ref": "./PublisherID.json"
      }
    },
    "pagination": {
      "$ref": "./Pagination.json"
    },
    "authors": {
      "type": "array",
      "description": "Array of Contrib objects",
      "items": {
        "$ref": "./Contrib.json"
      }
    },
    "otherContributor": {
      "type": "array",
      "description": "Array of Contrib/role pairs",
      "items": {
        "$ref": "./OtherContrib.json"
      }
    },
    "language": {
      "type": "string",
      "description": "ISO-639-1 country code of document language declaration"
    },
    "title": {
      "type": "array",
      "description": "Array of Title.json objects for multilingual support",
      "items": {
        "$ref": "./Title.json"
      }
    },
    "subtitle": {
      "type": "array",
      "description": "Array of Title.json objects for multilingual support",
      "items": {
        "$ref": "./Title.json"
      }
    },
    "abstract": {
      "type": "array",
      "items": {
        "$ref": "./Abstract.json"
      }
    },
    "comments": {
      "type": "array",
      "description": "Comments from authors, etc.",
      "items": {
        "$ref": "./Comment.json"
      }
    },
    "acknowledgements": {
      "type": "string",
      "description": "Acknowledgements, if fielded separately from body"
    },
    "references": {
      "type": "array",
      "description": "List of references in free text format",
      "items": {
        "type": "string"
      }
    },
    "backmatter": {
      "type": "array",
      "description": "Appendices, Supplementary material.",
      "items": {
        "type": "object",
        "properties": {
          "backType": {
            "type": "string"
          },
          "language": {
            "type": "string"
          },
          "body": {
            "type": "string"
          }
        }
      }
    },
    "astronomicalObjects": {
      "type": "array",
      "description": "List of astronomical objects in free text format",
      "items": {
        "type": "string"
      }
    },
    "esources": {
      "type": "array",
      "description": "Array of ESource.json objects",
      "items": {
        "$ref": "./ESource.json"
      }
    },
    "dataLinks": {
      "type": "array",
      "description": "Array of DataLink.json objects",
      "items": {
        "$ref": "./DataLink.json"
      }
    },
    "doctype": {
      "type": "string",
      "description": "This will only be required if we set doctype at parsing",
      "enum": [
        "article",
        "eprint",
        "phdthesis",
        "mastersthesis",
        "book",
        "inbook",
        "proceedings",
        "inproceedings",
        "software",
        "talk",
        "abstract",
        "proposal",
        "pressrelease",
        "circular",
        "newsletter",
        "catalog",
        "misc",
        "techreport",
        "nonarticle",
        "dataset"
      ]
    },
    "keywords": {
      "type": "array",
      "description": "Array of Keyword.json objects",
      "items": {
        "$ref": "./Keyword.json"
      }
    },
    "copyright": {
      "type": "object",
      "properties": {
        "status": {
          "type": "boolean"
        },
        "statement": {
          "type": "string"
        }
      }
    },
    "openAccess": {
      "$ref": "./OpenAccess.json"
    },
    "pubnote": {
      "type": "string"
    },
    "funding": {
      "type": "array",
      "description": "Array of Funder.json objects",
      "items": {
        "$ref": "./Funder.json"
      }
    },
    "version": {
      "type": "string"
    }
  },
  "required": [
    "recordData",
    "title",
    "pubDate",
    "publication"
  ],
  "additionalProperties": false
}

=== adsabs/ingest_data_model/test_data/wiley_jgra_58674.json
{
  "abstract": [
    {
      "atext": "Abstract Polarization and propagation characteristics of ultra\u2010low frequency (ULF, $\\simeq 1-1000$ mHz) waves are conventionally studied using arrays of ground\u2010based magnetometers. However, the ground magnetometer observations are subject to distortions due to polarization rotation and spatial integration effects caused by the transition of the magnetohydrodynamic wave into an electromagnetic wave at the lower ionospheric boundary. In contrast, high\u2010frequency (3\u201330 MHz) radars, like those comprising the Super Dual Auroral Radar Network (SuperDARN), are capable of direct observations of the ULF wave characteristics at ionospheric altitudes via measuring plasma drift velocity variations caused by the wave's electric field. In this work, we use multi\u2010beam data from SuperDARN Hokkaido East, Hokkaido West, and Christmas Valley West radars to identify the dominant polarization modes as well as azimuthal wave numbers of evening\u2010night\u2010side\u2010morning ULF waves in the Pc5 frequency band (1.67\u20136.67 mHz) propagating over sub\u2010auroral and mid\u2010latitude regions. The observed statistical characteristics of these waves point at the solar wind dynamic pressure variations and Kelvin\u2010Helmholtz instability at the magnetopause as their potential principal sources, although the drift\u2010bounce resonance with trapped energetic ions may contribute to the small\u2010scale part of the observed Pc5 wave population.",
      "language": "en"
    }
  ],
  "authors": [
    {
      "affiliation": [
        {
          "affPubRaw": "Institute for Space\u2010Earth Environmental Research, Nagoya University, Nagoya, Japan"
        }
      ],
      "name": {
        "given_name": "K.",
        "surname": "Morita"
      }
    },
    {
      "affiliation": [
        {
          "affPubRaw": "Institute for Space\u2010Earth Environmental Research, Nagoya University, Nagoya, Japan"
        },
        {
          "affPubRaw": "Institute of Space and Atmospheric Studies, University of Saskatchewan, Saskatoon, SK, Canada"
        }
      ],
      "attrib": {
        "email": "pasha.ponomarenko@usask.ca",
        "orcid": "0000-0001-8407-0193"
      },
      "name": {
        "given_name": "P.",
        "surname": "Ponomarenko"
      }
    },
    {
      "affiliation": [
        {
          "affPubRaw": "Institute for Space\u2010Earth Environmental Research, Nagoya University, Nagoya, Japan"
        }
      ],
      "attrib": {
        "orcid": "0000-0001-9842-5119"
      },
      "name": {
        "given_name": "N.",
        "surname": "Nishitani"
      }
    },
    {
      "affiliation": [
        {
          "affPubRaw": "Institute for Space\u2010Earth Environmental Research, Nagoya University, Nagoya, Japan"
        }
      ],
      "attrib": {
        "orcid": "0000-0001-8451-6941"
      },
      "name": {
        "given_name": "T.",
        "surname": "Hori"
      }
    },
    {
      "affiliation": [
        {
          "affPubRaw": "Thayer School of Engineering, Dartmouth College, Hanover, NH, USA"
        }
      ],
      "attrib": {
        "orcid": "0000-0003-1992-4118"
      },
      "name": {
        "given_name": "S. G.",
        "surname": "Shepherd"
      }
    }
  ],
  "copyright": {
    "statement": "\u00a9 2024. American Geophysical Union. All Rights Reserved.",
    "status": true
  },
  "editorialHistory": {
    "acceptedDate": "2024-08-29",
    "receivedDates": [
      "2024-03-01"
    ],
    "revisedDates": [
      "2024-07-21"
    ]
  },
  "language": "en",
  "pagination": {
    "electronicID": "e2024JA032592",
    "firstPage": "2024JA032592",
    "pageCount": "17"
  },
  "persistentIDs": [
    {
      "DOI": "10.1029/2024JA032592"
    }
  ],
  "pubDate": {
    "electrDate": "2024-09-12",
    "printDate": "2024-09-00"
  },
  "publication": {
    "ISSN": [
      {
        "issnString": "2169-9380",
        "pubtype": "print"
      },
      {
        "issnString": "2169-9402",
        "pubtype": "electronic"
      }
    ],
    "issueNum": "9",
    "pubName": "Journal of Geophysical Research: Space Physics",
    "pubYear": "2024",
    "volumeNum": "129"
  },
  "publisherIDs": [
    {
      "Identifier": "JGRA58674",
      "attribute": "unit"
    }
  ],
  "recordData": {
    "createdTime": "",
    "dataType": "",
    "loadFormat": "Wiley",
    "loadLocation": "",
    "loadType": "fromFile",
    "masterRecord": "",
    "parsedTime": "2026-03-20T17:00:00.000000Z",
    "recordOrigin": "",
    "UUID": "wxyz"
  },
  "references": [
    "<citation type=\"journal\" xml:id=\"jgra58674-cit-0001\"> <author> <familyName>Allan</familyName>, \t\t\t\t\t\t<givenNames>W.</givenNames> </author>, &amp; \t\t\t\t\t<author> <familyName>Poulter</familyName>, \t\t\t\t\t\t<givenNames>E. M.</givenNames> </author> ( \t\t\t\t\t<pubYear year=\"1992\">1992</pubYear>). \t\t\t\t\t<articleTitle>ULF waves\u2014Their relationship to the structure of the Earth\u2019s magnetosphere</articleTitle>. \t\t\t\t\t<journalTitle>Reports on Progress in Physics</journalTitle>, \t\t\t\t\t<vol>55</vol>( \t\t\t\t\t<issue>5</issue>), \t\t\t\t\t<pageFirst>533</pageFirst>\u2013 \t\t\t\t\t<pageLast>598</pageLast>. \t\t\t\t\t<url href=\"https://doi.org/10.1088/0034-4885/55/5/001\">https://doi.org/10.1088/0034\u20104885/55/5/001</url> </citation>",
    "<citation type=\"journal\" xml:id=\"jgra58674-cit-0002\"> <author> <familyName>Allan</familyName>, \t\t\t\t\t\t<givenNames>W.</givenNames> </author>, \t\t\t\t\t<author> <familyName>White</familyName>, \t\t\t\t\t\t<givenNames>S.</givenNames> </author>, &amp; \t\t\t\t\t<author> <familyName>Poulter</familyName>, \t\t\t\t\t\t<givenNames>E.</givenNames> </author> ( \t\t\t\t\t<pubYear year=\"1986\">1986</pubYear>). \t\t\t\t\t<articleTitle>Impulse\u2010excited hydromagnetic cavity and field\u2010line resonances in the magnetosphere</articleTitle>. \t\t\t\t\t<journalTitle>Planetary and Space Science</journalTitle>, \t\t\t\t\t<vol>34</vol>( \t\t\t\t\t<issue>4</issue>), \t\t\t\t\t<pageFirst>371</pageFirst>\u2013 \t\t\t\t\t<pageLast>385</pageLast>. \t\t\t\t\t<url href=\"https://doi.org/10.1016/0032-0633(86)90144-3\">https://doi.org/10.1016/0032\u20100633(86)90144\u20103</url> </citation>",
    "<citation type=\"journal\" xml:id=\"jgra58674-cit-0003\"> <author> <familyName>Chi</familyName>, \t\t\t\t\t\t<givenNames>P. J.</givenNames> </author>, &amp; \t\t\t\t\t<author> <familyName>Russell</familyName>, \t\t\t\t\t\t<givenNames>C. T.</givenNames> </author> ( \t\t\t\t\t<pubYear year=\"2005\">2005</pubYear>). \t\t\t\t\t<articleTitle>Travel\u2010time magnetoseismology: Magnetospheric sounding by timing the tremors in space</articleTitle>. \t\t\t\t\t<journalTitle>Geophysical Research Letters</journalTitle>, \t\t\t\t\t<vol>32</vol>( \t\t\t\t\t<issue>18</issue>), \t\t\t\t\t<eLocator>412</eLocator>. \t\t\t\t\t<url href=\"https://doi.org/10.1029/2005GL023441\">https://doi.org/10.1029/2005GL023441</url> </citation>",
    "<citation type=\"journal\" xml:id=\"jgra58674-cit-0004\"> <author> <familyName>Chisham</familyName>, \t\t\t\t\t\t<givenNames>G.</givenNames> </author>, \t\t\t\t\t<author> <familyName>Lester</familyName>, \t\t\t\t\t\t<givenNames>M.</givenNames> </author>, \t\t\t\t\t<author> <familyName>Milan</familyName>, \t\t\t\t\t\t<givenNames>S. E.</givenNames> </author>, \t\t\t\t\t<author> <familyName>Freeman</familyName>, \t\t\t\t\t\t<givenNames>M. P.</givenNames> </author>, \t\t\t\t\t<author> <familyName>Bristow</familyName>, \t\t\t\t\t\t<givenNames>W. A.</givenNames> </author>, \t\t\t\t\t<author> <familyName>Grocott</familyName>, \t\t\t\t\t\t<givenNames>A.</givenNames> </author>, et al. ( \t\t\t\t\t<pubYear year=\"2007\">2007</pubYear>). \t\t\t\t\t<articleTitle>A decade of the Super Dual Auroral Radar Network (SuperDARN): Scientific achievements, new techniques and future directions</articleTitle>. \t\t\t\t\t<journalTitle>Surveys in Geophysics</journalTitle>, \t\t\t\t\t<vol>28</vol>( \t\t\t\t\t<issue>1</issue>), \t\t\t\t\t<pageFirst>33</pageFirst>\u2013 \t\t\t\t\t<pageLast>109</pageLast>. \t\t\t\t\t<url href=\"https://doi.org/10.1007/s10712-007-9017-8\">https://doi.org/10.1007/s10712\u2010007\u20109017\u20108</url> </citation>",
    "<citation type=\"journal\" xml:id=\"jgra58674-cit-0005\"> <author> <familyName>Claudepierre</familyName>, \t\t\t\t\t\t<givenNames>S. G.</givenNames> </author>, \t\t\t\t\t<author> <familyName>Elkington</familyName>, \t\t\t\t\t\t<givenNames>S. R.</givenNames> </author>, &amp; \t\t\t\t\t<author> <familyName>Wiltberger</familyName>, \t\t\t\t\t\t<givenNames>M.</givenNames> </author> ( \t\t\t\t\t<pubYear year=\"2008\">2008</pubYear>). \t\t\t\t\t<articleTitle>Solar wind driving of magnetospheric ULF waves: Pulsations driven by velocity shear at the magnetopause</articleTitle>. \t\t\t\t\t<journalTitle>Journal of Geophysical Research</journalTitle>, \t\t\t\t\t<vol>113</vol>( \t\t\t\t\t<issue>A5</issue>), \t\t\t\t\t<eLocator>A05218</eLocator>. \t\t\t\t\t<url href=\"https://doi.org/10.1029/2007JA012890\">https://doi.org/10.1029/2007JA012890</url> </citation>",
    "<citation type=\"journal\" xml:id=\"jgra58674-cit-0006\"> <author> <familyName>Clausen</familyName>, \t\t\t\t\t\t<givenNames>L. B. N.</givenNames> </author>, &amp; \t\t\t\t\t<author> <familyName>Yeoman</familyName>, \t\t\t\t\t\t<givenNames>T. K.</givenNames> </author> ( \t\t\t\t\t<pubYear year=\"2009\">2009</pubYear>). \t\t\t\t\t<articleTitle>Comprehensive survey of Pc4 and Pc5 band spectral content in Cluster magnetic field data</articleTitle>. \t\t\t\t\t<journalTitle>Annales Geophysicae</journalTitle>, \t\t\t\t\t<vol>27</vol>( \t\t\t\t\t<issue>8</issue>), \t\t\t\t\t<pageFirst>3237</pageFirst>\u2013 \t\t\t\t\t<pageLast>3248</pageLast>. \t\t\t\t\t<url href=\"https://doi.org/10.5194/angeo-27-3237-2009\">https://doi.org/10.5194/angeo\u201027\u20103237\u20102009</url> </citation>",
